
package GDPServices;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchCountryException", targetNamespace = "http://week38.ties456.jyu.fi/")
public class NoSuchCountryException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchCountryException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchCountryException_Exception(String message, NoSuchCountryException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoSuchCountryException_Exception(String message, NoSuchCountryException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: GDPServices.NoSuchCountryException
     */
    public NoSuchCountryException getFaultInfo() {
        return faultInfo;
    }

}
